@"
Set-Item -Path Env:\Path -Value "$Env:Path;c:\var\lib\rancher\rke2\bin;c:\usr\local\bin"
Set-Item -Path Env:\CRI_CONFIG_FILE -Value "C:\var\lib\rancher\rke2\agent\etc\crictl.yaml"
Set-Item -Path Env:\CONTAINER_RUNTIME_ENDPOINT -Value "npipe:////./pipe/containerd-containerd"
"@ | Out-File -FilePath "$PSHOME\Profile.ps1"